### ISSUE TITLE
Invalid default configuration

### ISSUE THREAD

**Issue by vgottardi** [AtmelCSO/cryptoauth-openssl-engine#1]
Running `engine_atecc/ecc-test-main` with a new chip, locks it with a bad configuration. The problem is that slot 1 is marked as [locked (0xFE)](https://github.com/AtmelCSO/cryptoauth-openssl-engine/blob/master/engine_atecc/cryptoauthlib/lib/tls/atcatls.c#L202) before the key is generated in `atcatls_config_default()`.

**Comment by stevec-atmel** [comment]
Hi Victor, I just fixed this issue.  Thanks for the heads up.
